# Generated by Django 4.1.7 on 2023-03-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready')], default='processing', max_length=255)),
                ('num_of_records', models.IntegerField(default=1)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to='media/datasets/%Y/%m/%d/')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_schemas.dataschema')),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('full_name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('domain_name', 'Domain name'), ('phone_number', 'Phone number'), ('company_name', 'Company name'), ('text', 'Text'), ('integer', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=50)),
                ('sentences_num', models.IntegerField(default=1)),
                ('start_num', models.IntegerField(blank=True, null=True)),
                ('end_num', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_schemas.dataschema')),
            ],
        ),
    ]
