# Generated by Django 4.1.7 on 2023-03-12 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacolumn',
            name='data_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_column', to='data_schemas.dataschema'),
        ),
    ]
