# Generated by Django 4.1.7 on 2023-03-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0005_alter_datacolumn_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacolumn',
            name='end_num',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='start_num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
